//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtgtools.Tests {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CardSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CardSamples() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mtgtools.Tests.CardSamples", typeof(CardSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Bane of Bala Ged&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{7}&quot;,
        ///  &quot;Cmc&quot;:7.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Whenever Bane of Bala Ged attacks, defending player exiles two permanents he or she controls.&quot;,
        ///  &quot;Flavor&quot;:&quot;The continent of Bala Ged was ravaged by massive Eldrazi of Ulamog&apos;s lineage, its lush jungles and cascading rive [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string BaneOfBalaGed {
            get {
                return ResourceManager.GetString("BaneOfBalaGed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Elvish Spirit Guide&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{2}{G}&quot;,
        ///  &quot;Cmc&quot;:3.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Elf Spirit&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Elf&quot;,
        ///	 &quot;Spirit&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;Exile Elvish Spirit Guide from your hand: Add {G} to your mana pool.&quot;,
        ///  &quot;Flavor&quot;:&quot;\&quot;We are never without guidance, if we but seek it.\&quot;\n—Taaveti of Kelsinko, Elvish Hunter&quot;,
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ElvishSpiritGuide {
            get {
                return ResourceManager.GetString("ElvishSpiritGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Forest&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Basic Land — Forest&quot;,
        ///  &quot;Supertypes&quot;:[  
        ///	 &quot;Basic&quot;
        ///  ],
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Forest&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Basic Land&quot;,
        ///  &quot;Text&quot;:null,
        ///  &quot;Flavor&quot;:null,
        ///  &quot;Artist&quot;:&quot;John Avon&quot;,
        ///  &quot;Number&quot;:&quot;246&quot;,
        ///  &quot;Power&quot;:null,
        ///  &quot;Toughness&quot;:null,
        ///  &quot;Loyalty&quot;:null,
        ///  &quot;Layout&quot;:&quot;normal&quot;,
        ///  &quot;Multiverseid&quot;:195158,
        ///  &quot;Variations&quot;:[  
        ///	 &quot;201962&quot;,
        ///	 &quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Forest {
            get {
                return ResourceManager.GetString("Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Ghost Quarter&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Land&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{T}, Sacrifice Ghost Quarter: Destroy target land. Its controller may search his or her library for a basic land card, put it onto the battlefield, then shuffle his or her library.&quot;,
        ///  &quot;Flavor&quot;:&quot;Deserted, but not uninhabited.&quot;, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string GhostQuarter {
            get {
                return ResourceManager.GetString("GhostQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Slawomir Maniak&quot;,
        ///	&quot;cmc&quot;: 0,
        ///	&quot;flavor&quot;: &quot;Each of these intricate mechanical petals stores enough power to supply all of Ghirapur, if only for a fleeting moment.&quot;,
        ///	&quot;id&quot;: &quot;918aa0f2704c7e02f33e0ea7087c219bdbe22d4a&quot;,
        ///	&quot;imageName&quot;: &quot;lotus petal&quot;,
        ///	&quot;layout&quot;: &quot;normal&quot;,
        ///	&quot;legalities&quot;: [
        ///	  {
        ///		&quot;format&quot;: &quot;Commander&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Legacy&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Tempest Block&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Vin [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonArtifact {
            get {
                return ResourceManager.GetString("JsonArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Wesley Burt&quot;,
        ///	&quot;cmc&quot;: 1,
        ///	&quot;colorIdentity&quot;: [
        ///	  &quot;G&quot;
        ///	],
        ///	&quot;colors&quot;: [
        ///	  &quot;Green&quot;
        ///	],
        ///	&quot;flavor&quot;: &quot;\&quot;Life grows everywhere. My kin merely find those places where it grows strongest.\&quot;\n—Nissa Revane&quot;,
        ///	&quot;foreignNames&quot;: [
        ///	  {
        ///		&quot;language&quot;: &quot;Chinese Simplified&quot;,
        ///		&quot;name&quot;: &quot;妖精秘教徒&quot;,
        ///		&quot;multiverseid&quot;: 383513
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;Chinese Traditional&quot;,
        ///		&quot;name&quot;: &quot;妖精秘教徒&quot;,
        ///		&quot;multiverseid&quot;: 383797
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;German&quot;,
        ///		&quot;name&quot;: &quot;Elfen-Mystiker&quot;,
        ///		&quot;multiverseid&quot;: [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonCreature {
            get {
                return ResourceManager.GetString("JsonCreature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Christine Choi&quot;,
        ///	&quot;cmc&quot;: 3,
        ///	&quot;colorIdentity&quot;: [
        ///	  &quot;R&quot;
        ///	],
        ///	&quot;colors&quot;: [
        ///	  &quot;Red&quot;
        ///	],
        ///	&quot;id&quot;: &quot;8f73d710a4397d4e809d862d192217afd5d3e75f&quot;,
        ///	&quot;imageName&quot;: &quot;blood moon&quot;,
        ///	&quot;layout&quot;: &quot;normal&quot;,
        ///	&quot;legalities&quot;: [
        ///	  {
        ///		&quot;format&quot;: &quot;Commander&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Legacy&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Modern&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Vintage&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  }
        ///	],
        ///	&quot;manaCost&quot;: &quot;{2}{R}&quot;,
        ///	&quot;mciNumber&quot;: &quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonEnchantment {
            get {
                return ResourceManager.GetString("JsonEnchantment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Noah Bradley&quot;,
        ///	&quot;cmc&quot;: 1,
        ///	&quot;colorIdentity&quot;: [
        ///	  &quot;G&quot;
        ///	],
        ///	&quot;colors&quot;: [
        ///	  &quot;Green&quot;
        ///	],
        ///	&quot;flavor&quot;: &quot;\&quot;The prohibition of unnecessary tossing of the citizenry by giants shall also extend to spontaneous giants.\&quot;\n—Isperia&apos;s Edict, provision VII.789.2&quot;,
        ///	&quot;foreignNames&quot;: [
        ///	  {
        ///		&quot;language&quot;: &quot;Russian&quot;,
        ///		&quot;name&quot;: &quot;Исполинский Рост&quot;,
        ///		&quot;multiverseid&quot;: 355313
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;Chinese Traditional&quot;,
        ///		&quot;name&quot;: &quot;變巨術&quot;,
        ///		&quot;multiverseid&quot;: 355587
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;German&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonInstant {
            get {
                return ResourceManager.GetString("JsonInstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Howard Lyon&quot;,
        ///	&quot;cmc&quot;: 0,
        ///	&quot;id&quot;: &quot;47e1a5391bc529fd926be9f7237a6b99039d571c&quot;,
        ///	&quot;imageName&quot;: &quot;strip mine&quot;,
        ///	&quot;layout&quot;: &quot;normal&quot;,
        ///	&quot;legalities&quot;: [
        ///	  {
        ///		&quot;format&quot;: &quot;Commander&quot;,
        ///		&quot;legality&quot;: &quot;Legal&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Legacy&quot;,
        ///		&quot;legality&quot;: &quot;Banned&quot;
        ///	  },
        ///	  {
        ///		&quot;format&quot;: &quot;Vintage&quot;,
        ///		&quot;legality&quot;: &quot;Restricted&quot;
        ///	  }
        ///	],
        ///	&quot;mciNumber&quot;: &quot;43&quot;,
        ///	&quot;multiverseid&quot;: 409574,
        ///	&quot;name&quot;: &quot;Strip Mine&quot;,
        ///	&quot;number&quot;: &quot;43&quot;,
        ///	&quot;originalText&quot;: &quot;{T}: Add {C} to your mana pool.\n{T}, Sacrifice Str [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonLand {
            get {
                return ResourceManager.GetString("JsonLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Howard Lyon&quot;,
        ///	&quot;cmc&quot;: 2,
        ///	&quot;colorIdentity&quot;: [
        ///	  &quot;U&quot;,
        ///	  &quot;G&quot;
        ///	],
        ///	&quot;colors&quot;: [
        ///	  &quot;Blue&quot;,
        ///	  &quot;Green&quot;
        ///	],
        ///	&quot;foreignNames&quot;: [
        ///	  {
        ///		&quot;language&quot;: &quot;German&quot;,
        ///		&quot;name&quot;: &quot;Nissa, Hüterin der Elemente&quot;,
        ///		&quot;multiverseid&quot;: 427175
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;Spanish&quot;,
        ///		&quot;name&quot;: &quot;Nissa, encarnación de los elementos&quot;,
        ///		&quot;multiverseid&quot;: 427444
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;French&quot;,
        ///		&quot;name&quot;: &quot;Nissa, intendante des éléments&quot;,
        ///		&quot;multiverseid&quot;: 427713
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;Italian&quot;,
        ///		 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonPlaneswalker {
            get {
                return ResourceManager.GetString("JsonPlaneswalker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;artist&quot;: &quot;Raymond Swanland&quot;,
        ///	&quot;cmc&quot;: 1,
        ///	&quot;colorIdentity&quot;: [
        ///	  &quot;U&quot;
        ///	],
        ///	&quot;flavor&quot;: &quot;The Eldrazi twisted in a direction that had no name, and a frontal assault became a panicked rout.&quot;,
        ///	&quot;foreignNames&quot;: [
        ///	  {
        ///		&quot;language&quot;: &quot;Chinese Simplified&quot;,
        ///		&quot;name&quot;: &quot;滑越空间&quot;,
        ///		&quot;multiverseid&quot;: 407743
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;Chinese Traditional&quot;,
        ///		&quot;name&quot;: &quot;滑越空間&quot;,
        ///		&quot;multiverseid&quot;: 407929
        ///	  },
        ///	  {
        ///		&quot;language&quot;: &quot;German&quot;,
        ///		&quot;name&quot;: &quot;Durchschlüpfen&quot;,
        ///		&quot;multiverseid&quot;: 408115
        ///	  },
        ///	  {
        ///		&quot;lang [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonSorcery {
            get {
                return ResourceManager.GetString("JsonSorcery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Magus of the Library&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{G}{G}&quot;,
        ///  &quot;Cmc&quot;:2.0,
        ///  &quot;Colors&quot;:[  
        ///	 &quot;Green&quot;
        ///  ],
        ///  &quot;ColorIdentity&quot;:[  
        ///	 &quot;G&quot;
        ///  ],
        ///  &quot;Type&quot;:&quot;Creature — Human Wizard&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Human&quot;,
        ///	 &quot;Wizard&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{T}: Draw a card. Activate this ability only if you have exactly seven cards in hand.&quot;,
        ///  &quot;Flavor&quot;:&quot;The ancient books slowly crumbled, their se [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MagusOfTheLibrary {
            get {
                return ResourceManager.GetString("MagusOfTheLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Spawning Bed&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:null,
        ///  &quot;Cmc&quot;:0.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Land&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Land&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:null,
        ///  &quot;Rarity&quot;:&quot;Uncommon&quot;,
        ///  &quot;Text&quot;:&quot;{T}: Add {C} to your mana pool.\n{6}, {T}, Sacrifice Spawning Bed: Create three 1/1 colorless Eldrazi Scion creature tokens. They have \&quot;Sacrifice this creature: Add {C} to your mana pool.\&quot;&quot;,
        ///  &quot;Flavor&quot;:&quot;Young Eldrazi crawl forth from the dust, compelled by a  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SpawningBed {
            get {
                return ResourceManager.GetString("SpawningBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {  
        ///  &quot;Name&quot;:&quot;Thought-Knot Seer&quot;,
        ///  &quot;Names&quot;:null,
        ///  &quot;ManaCost&quot;:&quot;{3}{C}&quot;,
        ///  &quot;Cmc&quot;:4.0,
        ///  &quot;Colors&quot;:null,
        ///  &quot;ColorIdentity&quot;:null,
        ///  &quot;Type&quot;:&quot;Creature — Eldrazi&quot;,
        ///  &quot;Supertypes&quot;:null,
        ///  &quot;Types&quot;:[  
        ///	 &quot;Creature&quot;
        ///  ],
        ///  &quot;Subtypes&quot;:[  
        ///	 &quot;Eldrazi&quot;
        ///  ],
        ///  &quot;Rarity&quot;:&quot;Rare&quot;,
        ///  &quot;Text&quot;:&quot;({C} represents colorless mana.)\nWhen Thought-Knot Seer enters the battlefield, target opponent reveals his or her hand. You choose a nonland card from it and exile that card.\nWhen Thought-Knot Seer leaves the battlefiel [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ThoughtKnotSeer {
            get {
                return ResourceManager.GetString("ThoughtKnotSeer", resourceCulture);
            }
        }
    }
}
